name: CI

on:
  workflow_run:
    workflows: [ "Validate tags" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: update tags
        run: |
            declare -A directories_and_urls=(
              ["tokens"]="URL_1 URL_2"
              ["accounts"]="URL_3 URL_4"
            )
          
            # Loop over each directory and its corresponding URLs
            for dir in "${!directories_and_urls[@]}"; do
              # Merge JSON files in the directory
              jq -s 'flatten' "$dir"/*.json > merged.json
          
              # Iterate over URLs and upload the merged file
              for url_key in ${directories_and_urls[$dir]}; do
                curl -X 'POST' \
                     "${{ secrets[$url_key] }}" \
                     -H 'accept: application/json' \
                     -H 'Content-Type: multipart/form-data' \
                     -F 'file=@merged.json;type=application/json'
              done
          
              # Remove the merged file after processing
              rm merged.json
            done
          
