name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          apt-get update && apt-get install jq;
          jq -s 'flatten' *.json > merged.json;

          curl -F "file=@merged.json" https://api-stage.dex.guru/v2/tokens/add_token_tags;
          curl -F "file=@merged.json" https://api.dex.guru/v2/tokens/add_token_tags;

          rm merged.json;
