name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["test"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Run a multi-line script
        run: |
          jq -s 'flatten' *.json > merged.json;

          curl -F "file=@merged.json" ${{ secrets.URL_1 }};
          curl -F "file=@merged.json" ${{ secrets.URL_2 }};

          rm merged.json;
