name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: update tags
        run: |
          echo pwd; pwd;
          echo ls; ls;
          jq -s 'flatten' *.json > merged.json;

          curl -F "file=@merged.json" ${{ secrets.URL_1 }};
          curl -F "file=@merged.json" ${{ secrets.URL_2 }};

          rm merged.json;
